version: "3.7"

services:
  jamjuice-komodo-node:
    build:
      context: ./jamjuice-komodo-node
      args:
        - BLOCKCHAIN_DATA_PATH=${DATA_PATH}/${AC_NAME}
        - P2P_PORT=${KOMODO_SMARTCHAIN_NODE_P2P_PORT}
        - RPC_PORT=${KOMODO_SMARTCHAIN_NODE_RPC_PORT}
    image: jamjuice-komodo-node:test
    env_file:
     - ./instance.XX_CLONE_XX.env
    environment:
      - AC_CC=2
      - AC_PUBKEY=038afbc819aecfb3d65acdf270f755c9279d69d4a27293f10889264b8bd6c1fae2
      - AC_PUBLIC=${AC_PUBLIC}
      - AC_ADAPTIVEPOW=${AC_ADAPTIVEPOW}
      - AC_STAKED=${AC_STAKED}
      - AC_REWARD=${AC_REWARD}
      - AC_SUPPLY=${AC_SUPPLY}
      - BLOCKCHAIN_DATA_PATH=${DATA_PATH}/${AC_NAME}
      - ADD_NODE_1=${ADD_NODE_1}
      - ADD_NODE_2=${ADD_NODE_2}
      - THIS_NODE_WALLET=${THIS_NODE_WALLET}
      - THIS_NODE_PUBKEY=${THIS_NODE_PUBKEY}
      - THIS_NODE_WIF=${THIS_NODE_WIF}
      - BLOCKNOTIFY_DIR=${BLOCKNOTIFY_DIR}
      - BLOCKNOTIFY_CHAINSYNC_LIMIT=${BLOCKNOTIFY_CHAINSYNC_LIMIT}
      - HOUSEKEEPING_ADDRESS=${HOUSEKEEPING_ADDRESS}
      - KOMODO_SMARTCHAIN_NODE_USERNAME=${KOMODO_SMARTCHAIN_NODE_USERNAME}
      - KOMODO_SMARTCHAIN_NODE_PASSWORD=${KOMODO_SMARTCHAIN_NODE_PASSWORD}
      - KOMODO_SMARTCHAIN_NODE_RPC_PORT=${KOMODO_SMARTCHAIN_NODE_RPC_PORT}
      - KOMODO_SMARTCHAIN_NODE_P2P_PORT=${KOMODO_SMARTCHAIN_NODE_P2P_PORT}
    entrypoint:
      - "bash"
      - "-c"
      - |
        /opt/komodo/komodo/src/komodod \
        -ac_cc=$${AC_CC} \
        -ac_name=${AC_NAME} \
        -ac_pubkey=$${AC_PUBKEY} \
        -ac_public=$${AC_PUBLIC} \
        -ac_adaptivepow=${AC_ADAPTIVEPOW} \
        -ac_staked=${AC_STAKED} \
        -ac_reward=$${AC_REWARD} \
        -ac_supply=$${AC_SUPPLY} \
        -addnode=$${ADD_NODE_1} \
        -addnode=$${ADD_NODE_2} \
        -datadir=$${BLOCKCHAIN_DATA_PATH} \
        -rpcallowip=${DOCKER_KOMODO_SMARTCHAIN_NETWORK_SUBNET} \
        -rpcallowip=127.0.0.1 \
        -rpcbind=0.0.0.0 \
        -rpcpassword=${KOMODO_SMARTCHAIN_NODE_PASSWORD} \
        -rpcport=${KOMODO_SMARTCHAIN_NODE_RPC_PORT} \
        -rpcuser=${KOMODO_SMARTCHAIN_NODE_USERNAME} \
        -server=1 \
        -timeout=18000 \
        -txindex=1 \
        -blocknotify="/opt/komodo/customer-smartchain-nodes-blocknotify/status.sh %s" \
        -pubkey=$${THIS_NODE_PUBKEY}
    ports:
      - "${KOMODO_SMARTCHAIN_NODE_P2P_PORT}"
      - "${KOMODO_SMARTCHAIN_NODE_RPC_PORT}"
    networks:
      komodo:
          ipv4_address: ${KOMODO_SMARTCHAIN_NODE_IPV4_ADDR}
    volumes:
      - ./jamjuice-komodo-node/data/instance/XX_CLONE_XX:${DATA_PATH}/${AC_NAME}
      - ./customer-smartchain-nodes-blocknotify:/opt/komodo/customer-smartchain-nodes-blocknotify
  blocknotify-python:
    build:
      context: ./blocknotify-python
      args:
        ENV: dev
    env_file:
     - ./instance.XX_CLONE_XX.env
    command: /code/run.sh
    #command: /bin/bash
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    depends_on:
      - jamjuice-komodo-node
      - import-api
    networks:
      komodo:
        ipv4_address: ${BLOCKNOTIFY_PYTHON_IPV4_ADDR}
  import-api:
    build:
      context: ./import-api
      args:
        ENV: dev
    env_file:
     - ./instance.XX_CLONE_XX.env
    command: python manage.py runserver 0.0.0.0:8777
    environment:
      - DJANGO_HOST=*
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./import-api/src/:/code
    ports:
      - "8777"
    links:
      - db:db
    depends_on:
      - db
    networks:
      komodo:
          ipv4_address: ${IMPORT_API_IPV4_ADDR}
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      komodo:
        ipv4_address: ${POSTGRES_IPV4_ADDR}
networks:
  komodo:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_KOMODO_SMARTCHAIN_NETWORK_SUBNET}
